-- PHẦN 3 CÂU LỆNH SELECT
--TRUY VẤN CƠ BẢN
--3.1.1 TRUY VẤN ĐƠN GIẢN
--1.
SELECT *
FROM NHANVIEN
WHERE PHG = 30

--2.
SELECT MANV, HONV + ' ' + TENNV AS HOTEN, LUONG
FROM NHANVIEN
WHERE	LUONG > 25000

--3.
SELECT MANV, HONV + ' ' + TENNV AS HOTEN, LUONG , PHG
FROM NHANVIEN
WHERE	LUONG > 65000 AND PHG = 10 OR LUONG > 70000 AND PHG = 20

--4.
SELECT MANV, HONV + ' ' + TENNV AS HOTEN,DCHI
FROM NHANVIEN
WHERE DCHI=N'Tp.Hồ Chí Minh'

--5.
SELECT HONV + ' ' + TENNV AS HOTEN 
FROM NHANVIEN
WHERE HONV LIKE N'N%'
--6
SELECT NGSINH, DCHI
FROM NHANVIEN
WHERE HONV + ' '+ TENNV = 'LE 1'
--7
SELECT HONV + ' ' + TENNV AS HOTEN
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1955 AND 1990


SELECT *
FROM NHANVIEN

--8
 SELECT HONV + ' ' + TENNV AS HOTEN,YEAR(NGSINH) AS NSINH
 FROM NHANVIEN
 --9 C1: datediff
SELECT HONV + ' ' + TENNV AS HOTEN, DATEDIFF(year,NGSINH,GETDATE()) AS TUOI
FROM NHANVIEN

--9 C2
SELECT HONV + ' ' + TENNV AS HOTEN, YEAR(GETDATE())-YEAR(NGSINH)  AS TUOI
FROM NHANVIEN


-- 3.1.2 TRUY VẤN CÓ SỬ DỤNG PHÉP KẾT NỐI
--10
SELECT nV.PHG , PGB.TENPHG 
FROM NHANVIEN NV,PHONGBAN PGB
WHERE PGB.MAPHG = NV.PHG
--11
SELECT NV.HONV +' ' + TENNV AS TRUONGPHONG,PGB.TENPHG
FROM NHANVIEN NV,PHONGBAN PGB
WHERE NV.MANV = PGB.TRPHG
--12
SELECT NV.HONV +' ' + TENNV AS HOTEN, PGB.TENPHG
FROM NHANVIEN NV, PHONGBAN PGB
WHERE NV.PHG = PGB.MAPHG AND PGB.MAPHG = 30
--13
SELECT NV.HONV +' ' + TENNV AS HOTEN,PGB.TRPHG ,PGB.TENPHG,PGB.NG_NHANCHUC,DA.TENDA
FROM NHANVIEN NV,PHONGBAN PGB, DEAN DA
WHERE NV.MA_NQL= PGB.TRPHG AND PGB.MAPHG = DA.PHONG AND DA.DDIEM_DA = 'NHA TRANG'
--14
SELECT NV.HONV +' ' + TENNV AS HOTEN,NV.PHAI,NGUOITHAN.TENTN
FROM NHANVIEN NV, THANNHAN NGUOITHAN
WHERE NV.MANV=NGUOITHAN.MA_NVIEN AND NV.PHAI='NU'
--15--CACH 1: CÁCH KHÔNG NÊN SỬ DỤNG TRONG CÔNG VIỆC 
SELECT NV.HONV + ' '+NV.TENNV AS HOTEN_NV, NQL.HONV+' '+NQL.TENNV AS HOTEN_NQL
FROM NHANVIEN NV, NHANVIEN NQL
WHERE NV.MA_NQL=NQL.MANV


--CÁCH 2: SỬ DỤNG PHỔ BIẾN TRONG CÔNG VIỆC -- INNER JOIN CÓ THỂ VIẾT NGẮN GỌN LÀ JOIN VÀ JOIN PHẢI CÓ ON(LÀ BIỂU THỨC ĐIỀU KIỆN CỦA DỮ LIỆU CẦN TRUY CẬP)
SELECT NV.HONV + ' '+NV.TENNV AS HOTEN_NV, NQL.HONV+' '+NQL.TENNV AS HOTEN_NQL
FROM NHANVIEN NV
JOIN NHANVIEN NQL
ON NV.MA_NQL = NQL.MANV

-- 3.2 GOM NHÓM 
--19
SELECT COUNT(MADA) AS SO_DEAN
FROM DEAN
--20
SELECT PGB.TENPHG,COUNT(DA.MADA) AS SoLuongDeAn
FROM PHONGBAN PGB,DEAN DA
WHERE PGB.MAPHG =DA.PHONG AND DA.PHONG = 20
GROUP BY PGB.TENPHG
--21
SELECT AVG(LUONG) AS TIEN_LUONG_TB
FROM NHANVIEN
WHERE PHAI ='NU'
--22
--CACH 1 ÁP DỤNG TRUY VẤN CƠ BẢN
SELECT  COUNT(TN.TENTN) AS SoThanNhan
FROM NHANVIEN NV,THANNHAN TN
WHERE NV.MANV=TN.MA_NVIEN AND NV.HONV + ' ' + NV.TENNV ='LE 1'


--22 CACH GROUP BY
SELECT NV.HONV +' ' +NV.TENNV AS HOTEN,TN.TENTN,COUNT(TN.TENTN) AS SoThanNhan
FROM NHANVIEN NV,THANNHAN TN
WHERE NV.MANV = TN.MA_NVIEN AND NV.HONV+ ' '+ NV.TENNV LIKE'LE 1'
GROUP BY NV.HONV,NV.TENNV,TN.TENTN
--HAVING NV.HONV+ ' '+ NV.TENNV LIKE'LE 1'

--23
SELECT DA.TENDA,PC.MA_NVIEN,SUM(7*PC.THOIGIAN) AS tongThoiGianLamViec
FROM PHANCONG PC,DEAN DA
WHERE PC.SODA = DA.MADA
GROUP BY DA.TENDA,PC.MA_NVIEN


--24
--CACH 1
SELECT DA.TENDA,COUNT(PC.MA_NVIEN) AS SLNhanvienThamgia
FROM PHANCONG PC,DEAN DA
WHERE PC.SODA = DA.MADA
GROUP BY DA.TENDA

--DOAN CODE THU DE KIEM TRA KQ 
SELECT PC.MA_NVIEN,DA.TENDA,COUNT(PC.MA_NVIEN) AS SLNhanvienThamgia
FROM PHANCONG PC,DEAN DA
WHERE PC.SODA = DA.MADA
GROUP BY DA.TENDA,PC.MA_NVIEN

--25
SELECT NV.HONV+' '+NV.TENNV AS HotenNV,COUNT(TN.TENTN) AS SoLuongThanNhan
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.MANV = TN.MA_NVIEN
GROUP BY NV.HONV,NV.TENNV

--26
SELECT NV.HONV+' '+NV.TENNV,COUNT(DA.MADA) AS SOLUONGDEAN
FROM NHANVIEN NV, DEAN DA
WHERE NV.PHG = DA.PHONG
GROUP BY NV.HONV,NV.TENNV

--27

SELECT HONV+' '+TENNV AS HotenNV,COUNT(MA_NQL) AS Soluong_QuanLy
FROM NHANVIEN
GROUP BY HONV,TENNV

--28
SELECT PGB.TENPHG, AVG(NV.LUONG)
FROM PHONGBAN PGB,NHANVIEN NV
WHERE PGB.MAPHG = NV.PHG
GROUP BY PGB.TENPHG

--29
SELECT PGB.TENPHG,COUNT(NV.MANV) AS Soluong_NV,AVG(NV.LUONG) AS LuongtrungBinh
FROM PHONGBAN PGB, NHANVIEN NV
WHERE PGB.MAPHG = NV.PHG
GROUP BY PGB.TENPHG,NV.LUONG
HAVING AVG(NV.LUONG) > 30000

--30
SELECT PGB.TENPHG,COUNT(MADA) AS SoLuongDeAn
FROM PHONGBAN PGB, DEAN DA
WHERE PGB.MAPHG = DA.PHONG
GROUP BY PGB.TENPHG

--31
SELECT PGB.TENPHG,NV.HONV+ ' '+ NV.TENNV AS HoTenTruongPhong,COUNT(DA.MADA) AS SoLuongDeAn
FROM PHONGBAN PGB, DEAN DA , NHANVIEN NV
WHERE PGB.MAPHG = DA.PHONG AND PGB.TRPHG = NV.MANV
GROUP BY PGB.TENPHG,NV.HONV,NV.TENNV

--32
SELECT  PGB.TENPHG, COUNT(DA.MADA) AS SoLuongDeAn
FROM PHONGBAN PGB, DEAN DA, NHANVIEN NV
WHERE PGB.MAPHG = DA.PHONG AND NV.MANV = PGB.TRPHG
GROUP BY PGB.TENPHG
HAVING AVG(NV.LUONG) >66000

--33
SELECT DDIEM_DA,COUNT(MADA) AS SoDeAn
FROM DEAN
GROUP BY DDIEM_DA

-- CAU 34 VÀ CÂU 35 KHÔNG LÀM ĐƯỢC VÌ KHÔNG CÓ BẢNG CÔNG VIỆC

--3.3 Truy vấn lồng + gom nhóm (khó)

--36
SELECT PC.SODA, NV.HONV
FROM PHANCONG PC, NHANVIEN NV
WHERE NV.MANV = PC.MA_NVIEN AND NV.HONV ='LE'
UNION
SELECT DA.MADA, NV.HONV
FROM PHONGBAN PGB,NHANVIEN NV,DEAN DA
WHERE PGB.MAPHG = DA.PHONG AND NV.MANV = PGB.TRPHG AND NV.HONV='LE'

select
from
where





