--MODULE2:

CREATE TABLE NHANVIEN
(
	MANV	VARCHAR(9) NOT NULL,
	HONV	NVARCHAR(15),
	TENLOT	NVARCHAR(30),
	TENNV	NVARCHAR(30),
	NGSINH	SMALLDATETIME,
	DCHI	NVARCHAR(150),
	PHAI	NVARCHAR(3),
	LUONG	NUMERIC(18,0),
	MA_NQL	VARCHAR(9),
	PHG		VARCHAR(2),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)

);
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)

CREATE TABLE PHONGBAN
(
MAPHG			VARCHAR(2) NOT NULL,
TENPHG			NVARCHAR(20),
TRPHG			VARCHAR(9),
NG_NHANCHUC		SMALLDATETIME,
CONSTRAINT PK_PHONGBAN PRIMARY KEY(MAPHG),
CONSTRAINT FK_PHONGBAN_NHANVIEN FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)

);


CREATE TABLE PHANCONG
(
	MA_NVIEN	VARCHAR(9) NOT NULL,
	SODA		VARCHAR(2)	NOT NULL,
	THOIGIAN	NUMERIC(18,0),
	CONSTRAINT PK_PHANCONG PRIMARY KEY(MA_NVIEN,SODA),
	CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)

);
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_DEAN FOREIGN KEY(SODA) REFERENCES DEAN(MADA)

CREATE TABLE DEAN
(
MADA		VARCHAR(2) NOT NULL,
TENDA		NVARCHAR(50),
DDIEM_DA	VARCHAR(20),
PHONG		VARCHAR(20),
CONSTRAINT PK_DEAN	PRIMARY KEY(MADA)
);

CREATE TABLE THANNHAN
(
MA_NVIEN	VARCHAR(9) NOT NULL,
TENTN		VARCHAR(20) NOT NULL,
NGSINH		SMALLDATETIME,
PHAI		VARCHAR(3),
QUANHE		VARCHAR(15),
CONSTRAINT PK_THANNHAN PRIMARY KEY(MA_NVIEN,TENTN),
CONSTRAINT FK_THANNHAN_NHANVIEN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE DDIEM_PHG
(
MAPHG	VARCHAR(2)  NOT NULL,
DIADIEM	VARCHAR(20) NOT NULL,
CONSTRAINT PK_DDIEM_PHG	PRIMARY KEY(MAPHG,DIADIEM),
CONSTRAINT FK_DDIEM_PHG_PHONGBAN FOREIGN KEY(MAPHG)	REFERENCES PHONGBAN(MAPHG)


);

--module 3: các câu lệnh dml(ngôn ngữ thao tác dữ liệu)
--phần 1 các câu lệnh insert
--2
insert into NHANVIEN(MANV)
values('20'),('30')

INSERT INTO PHONGBAN(MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
VALUES ('2',N'Nhân Sự','10','2003/12/12')

--3
INSERT INTO PHONGBAN(MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
VALUES ('6',N'Kế Toán','20','2005/10/23'),
('7',N'Kỹ Thuật','30','2006/12/05')

--4
insert into DEAN(MADA)
values('8'),('9'),('10'),('11'),('12'),('13'),('14'),('15')

--5 làm bằng giao diện
--6 không có csdl adventureworks

--phần update
--cú pháp
/*
update ten bảng
set tên cột cần update
where điều kiện
*/
--1
update NHANVIEN
set DCHI = N'TP.Hồ Chí Minh'
where DCHI is null

--2
update NHANVIEN
set PHG=2
where MANV between 1 and 10

update NHANVIEN
set PHG = 6
where MANV between 11 and 40

update NHANVIEN
set PHG = 7
where MANV between 41 and 50

--3
update NHANVIEN
set NGSINH = '1985-01-01'
where NGSINH is null

--4
update NHANVIEN
set LUONG = 100000
where PHG = 7

update NHANVIEN
set LUONG =65000
where PHG = 6

update NHANVIEN
set LUONG = 85000
where PHG = 2

--5
update NHANVIEN
set MA_NQL =10
where PHG =6

update NHANVIEN
set MA_NQL =35
where PHG =7

update NHANVIEN
set MA_NQL =50
where PHG =2

update NHANVIEN
set MA_NQL = null
where MANV = 6
update NHANVIEN
set MA_NQL = null
where MANV = 2
update NHANVIEN
set MA_NQL = null
where MANV = 7