create table NHANVIEN
(
	MANV	VARCHAR(9)	NOT NULL,
	HONV	NVARCHAR(15),
	TENLOT	NVARCHAR(30),
	TENNV	NVARCHAR(30),
	NGSINH	SMALLDATETIME,
	DCHI	NVARCHAR(150),
	PHAI	NVARCHAR(3),
	LUONG	NUMERIC(18,0),
	MA_NQL	VARCHAR(9),
	PHG		VARCHAR(2),
	PRIMARY KEY(MANV),


);

ALTER TABLE NHANVIEN
ADD FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV),
FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)


GO
create table PHONGBAN
(
	MAPHG		VARCHAR(2)		NOT NULL,
	TENPHG		NVARCHAR(20),
	TRPHG		VARCHAR(9),
	NG_NHANCHUC	SMALLDATETIME,
	PRIMARY KEY(MAPHG),
	FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)


);
GO

CREATE TABLE PHANCONG
(
	MA_NVIEN	VARCHAR(9)		NOT NULL,
	SODA		VARCHAR(2)		NOT NULL,
	THOIGIAN	NUMERIC(18,0)	NOT NULL,
	PRIMARY KEY(MA_NVIEN,SODA),
	FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
);

ALTER TABLE PHANCONG
ADD FOREIGN KEY(SODA) REFERENCES DEAN(MADA);
GO
CREATE TABLE THANNHAN
(
	MA_NVIEN	VARCHAR(9)	NOT NULL,
	TENTN		VARCHAR(20)	NOT NULL,
	NGSINH		SMALLDATETIME,
	PHAI		VARCHAR(3),
	QUANHE		VARCHAR(15),
	PRIMARY KEY (MA_NVIEN,TENTN),
	FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)



);
GO
CREATE TABLE DEAN
(
	MADA		VARCHAR(2)	NOT NULL,
	TENDA		VARCHAR(50)	,
	DDIEM_DA	VARCHAR(20),
	PHONG		VARCHAR(2),
	PRIMARY KEY(MADA)


);
GO
CREATE TABLE DIADIEM_PHG
(
	MAPHG	VARCHAR(2)  NOT NULL,
	DIADIEM	VARCHAR(20)	NOT NULL,
	PRIMARY KEY(MAPHG,DIADIEM),
	FOREIGN KEY(MAPHG)	REFERENCES PHONGBAN(MAPHG)


);