create table NHANVIEN
(
	MANV	VARCHAR(9)	NOT NULL,
	HONV	NVARCHAR(15),
	TENLOT	NVARCHAR(30),
	TENNV	NVARCHAR(30),
	NGSINH	SMALLDATETIME,
	DCHI	NVARCHAR(150),
	PHAI	NVARCHAR(3),
	LUONG	NUMERIC(18,0),
	MA_NQL	VARCHAR(9),
	PHG		VARCHAR(2),
	PRIMARY KEY(MANV),


);

ALTER TABLE NHANVIEN
ADD FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV),
FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)


GO
create table PHONGBAN
(
	MAPHG		VARCHAR(2)		NOT NULL,
	TENPHG		NVARCHAR(20),
	TRPHG		VARCHAR(9),
	NG_NHANCHUC	SMALLDATETIME,
	PRIMARY KEY(MAPHG),
	FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)

);
GO

CREATE TABLE PHANCONG
(
	MA_NVIEN	VARCHAR(9)		NOT NULL,
	SODA		VARCHAR(2)		NOT NULL,
	THOIGIAN	NUMERIC(18,0),
	PRIMARY KEY(MA_NVIEN,SODA),
	FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(SODA) REFERENCES DEAN(MADA)
);

GO
CREATE TABLE THANNHAN
(
	MA_NVIEN	VARCHAR(9)	NOT NULL,
	TENTN		VARCHAR(20)	NOT NULL,
	NGSINH		SMALLDATETIME,
	PHAI		VARCHAR(3),
	QUANHE		VARCHAR(15),
	PRIMARY KEY (MA_NVIEN,TENTN),
	FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)



);
GO
CREATE TABLE DEAN
(
	MADA		VARCHAR(2)	NOT NULL,
	TENDA		VARCHAR(50)	,
	DDIEM_DA	VARCHAR(20),
	PHONG		VARCHAR(2),
	PRIMARY KEY(MADA),


);
GO
CREATE TABLE DIADIEM_PHG
(
	MAPHG	VARCHAR(2)  NOT NULL,
	DIADIEM	VARCHAR(20)	NOT NULL,
	PRIMARY KEY(MAPHG,DIADIEM),
	FOREIGN KEY(MAPHG)	REFERENCES PHONGBAN(MAPHG)


);


-- MODULE 3: PHẦN LỆNH INSERT
INSERT INTO PHONGBAN(TENPHG,MAPHG,NG_NHANCHUC)

VALUES(N'Nhân sự',10,'2003/12/12'),
(N'Kế toán',20,'2005/10/23'),
(N'Kỹ thuật',30,'2006/12/05')

INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES ('8','A','NHA TRANG','2'),
('9','B','NHA TRANG','3'),
('10','C','NHA TRANG','4'),
('11','D','NHA TRANG','5'),
('12','E','NHA TRANG','6'),
('13','F','NHA TRANG','1'),
('14','G','NHA TRANG','2'),
('15','H','NHA TRANG','7')


--PHẦN 2: LỆNH UPDATE
UPDATE NHANVIEN
SET DCHI =N'Tp.Hồ Chí Minh'

UPDATE NHANVIEN
SET PHG='10'
WHERE MANV BETWEEN 1 AND 10

UPDATE NHANVIEN
SET PHG='20'
WHERE MANV BETWEEN 11 AND 40

UPDATE NHANVIEN
SET PHG='30'
WHERE MANV BETWEEN 41 AND 50

UPDATE NHANVIEN
SET NGSINH ='1985/01/01'
WHERE NGSINH IS NULL
--4.
UPDATE NHANVIEN
SET LUONG = 100000
WHERE PHG = 30

UPDATE NHANVIEN
SET LUONG = 65000
WHERE PHG = 20

UPDATE NHANVIEN
SET LUONG = 70000
WHERE PHG = 10

--5.
UPDATE NHANVIEN
 SET MA_NQL= 2
 WHERE PHG = 10

 UPDATE NHANVIEN
 SET MA_NQL = 25
 WHERE PHG = 20

 UPDATE NHANVIEN
 SET MA_NQL = 30
 WHERE PHG = 30

 UPDATE NHANVIEN
 SET PHAI = 'NAM'
 WHERE MANV % 2 <> 0
 SELECT * FROM NHANVIEN

